name: Examples
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        allow_failure: [false]
        version: ['1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]
        include:
          - version: '1'
            os: macOS-latest
            arch: aarch64
        exclude:
          - version: '1'
            os: macOS-latest
            arch: x64
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: matrix.os == 'windows-latest'
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          brew install gfortran
        if: matrix.os == 'macOS-latest'
      - run: |
          julia --project=examples -e 'using Pkg; Pkg.instantiate(); include(joinpath("examples", "bmark_cutest.jl"))'
        if: matrix.os != 'windows-latest'
      - run: julia --project=examples -e 'using Pkg; Pkg.instantiate(); include(joinpath("examples", "bmark_ampl.jl"))'
      - run: julia --project=examples -e 'using Pkg; Pkg.instantiate(); include(joinpath("examples", "bmark_opt_problems.jl"))'
      - run: julia --project=examples -e 'using Pkg; Pkg.instantiate(); include(joinpath("examples", "bmark_opt_problems_jump.jl"))'
